//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPTennis.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bp_tennisEntities : DbContext
    {
        public bp_tennisEntities()
            : base("name=bp_tennisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<court> courts { get; set; }
        public DbSet<player> players { get; set; }
        public DbSet<session> sessions { get; set; }
        public DbSet<session_court_player> session_court_player { get; set; }
        public DbSet<session_players> session_players { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<comments> comments1 { get; set; }
    }
}
