//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPTennis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class court
    {
        public court()
        {
            this.session_court_player = new HashSet<session_court_player>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<session_court_player> session_court_player { get; set; }
    }
}
