//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPTennis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public player()
        {
            this.session_court_player = new HashSet<session_court_player>();
            this.session_player = new HashSet<session_player>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string gender { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<session_court_player> session_court_player { get; set; }
        public virtual ICollection<session_player> session_player { get; set; }
    }
}
