//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPTennis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class session
    {
        public session()
        {
            this.session_players = new HashSet<session_players>();
        }
    
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string courts { get; set; }
    
        public virtual ICollection<session_players> session_players { get; set; }
    }
}
