//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPTennis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class session_court_player
    {
        public int id { get; set; }
        public int session_id { get; set; }
        public int court_id { get; set; }
        public int player_id { get; set; }
        public bool in_progress { get; set; }
    
        public virtual court court { get; set; }
        public virtual player player { get; set; }
        public virtual session session { get; set; }
    }
}
